---
- name: Bigpanda incident events
  hosts: all
  sources:
    - bigpanda_incidents:
        api_token: 
        environment_id: 
        interval: 5
        return_first_poll: false

  rules:
    - name: R1 - Debug all
      condition: event.meta is defined
      action:
        debug: