---
- name: Bigpanda ops
  hosts: localhost
  connection: localhost
  vars:
    bp_token: 
    bp_incident: 
    bp_environment: 
    bp_user_email: 
  tasks:

  - name: Get Incident from BigPanda API
    ansible.builtin.uri:
      url: "https://api.bigpanda.io/resources/v2.0/environments/{{ bp_environment }}/incidents/{{ bp_incident }}"
      method: GET
      headers:
        Authorization: "Bearer {{ bp_token }}"
      return_content: true
    register: incident

  - name: Debug incident
    ansible.builtin.debug:
      var: incident


  # - name: Take ownership of an incident

  # - name: Add a comment to an incident
  #   bigpanda.incident.comment:
  #     incident_id: "{{ bp_incident }}"
  #     comment: "This is a test comment."
  #     api_token: "{{ bp_token }}"
  #     environment_id: "{{ bp_environment }}"